trigger:
  batch: true
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: OpsGuildPipelineTools
      type: git
      name: Engineering/opsguild.pipeline-tools
      ref: refs/heads/main
    - repository: templates
      type: github
      name: osisoft/OSI-Samples
      endpoint: osisoft/OSI-Samples

variables:
  - template: '/miscellaneous/build_templates/variables.yml@templates'
  - name: analysisProject
    value: PI_AFSDKCustomCalcEvent_DotNet

jobs:
  - job: Tests
    pool:
      name: 00-OSIManaged-Containers
      demands: Agent.OS -equals Windows_NT
    steps:
      - checkout: self
      - checkout: OpsGuildPipelineTools

      - template: '/miscellaneous/build_templates/appsettings.yml@templates'
      
      - template: '/Templates/Utilities/InstallAFSDK.step.v0.yml@OpsGuildPipelineTools'

      - task: NuGetCommand@2
        displayName: 'nuget restore'
        inputs:
          command: 'restore'
          restoreSolution: '**/*.sln'

      - task: DotNetCoreCLI@2
        displayName: 'Run tests'
        inputs:
          command: test
          publishTestResults: true
          testRunTitle: '$(Agent.JobName) on $(Agent.OS)'
          projects: C:\agent\_work\1\s\sample-afsdk-event_triggered_calculation-dotnet\EventTriggeredCalc.sln

  - job: Analysis
    pool:
      name: 00-OSIManaged-Test
      demands: COMPUTERNAME -equals $(buildAgent)

    steps:
    - task: NuGetCommand@2
      displayName: 'nuget restore'
      inputs:
        command: 'restore'
        restoreSolution: '**/*.sln'

    - task: VSBuild@1
      displayName: 'Build solution'
      inputs: 
        vsVersion: 16.0

    - template: '/miscellaneous/build_templates/binskim.yml@templates'

    - template: '/miscellaneous/build_templates/analysis.yml@templates'
